name: docs links on maas.io/docs

on: pull_request

jobs:
  check-links:
    if: github.repository == 'canonical-web-and-design/maas.io'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Install linkchecker
        run: sudo pip install LinkChecker

      - name: Run linkchecker
        run: linkchecker --threads 2 --ignore-url "https://res.cloudinary.com*" --ignore-url '.*&start=.*' --ignore-url /q_auto --ignore-url /fl_sanitize --ignore-url /w_* --ignore-url /h_* --ignore-url "https://assets.ubuntu.com$" --check-extern --no-warnings https://maas.io/docs

      - name: Send message on failure
        if: failure()
        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" ${{ secrets.BOT_URL }}?room=test-bot-channel
